const profile = 
[
{
  id:1,
  img:require('../assets/bill.png'),
  heading:'bills',
  backgroundColor:'red'
},
{
  id:2,
  img:require('../assets/taxi.png'),
  heading:'driving',
  backgroundColor:'red'
},
{
  id:3,
  img:require('../assets/logistic.png'),
  heading:'logistic',
  backgroundColor:'red'
},
{
  id:4,
  img:require('../assets/logistic.png'),
  heading:'home',
  backgroundColor:'red'
},
{
  id:5,
  img:require('../assets/3081144.png'),
  heading:'Food',
  backgroundColor:'red'
},
{
    id:5,
    img:require('../assets/3081144.png'),
    heading:'fuel',
    backgroundColor:'red'
  }
]
export {profile}
